// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "The file is generated by the project template.", Scope = "member", Target = "~F:RoslyJump.TextAdornment1TextViewCreationListener.editorAdornmentLayer")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "The file is generated by the project template.", Scope = "member", Target = "~F:RoslyJump.TextAdornment1TextViewCreationListener.editorAdornmentLayer")]
